export const customerTemplates = [
  {
    name: 'John Smith',
    email: 'john.smith@example.com',
    phone: '07123456789',
    company: 'Tech Solutions Ltd',
    address: '123 Oxford Street, London',
  },
  {
    name: 'Sarah Johnson',
    email: 'sarah.johnson@example.com',
    phone: '07234567890',
    company: 'Creative Designs Inc',
    address: '456 King Road, Manchester',
  },
  {
    name: 'Michael Brown',
    email: 'michael.brown@example.com',
    phone: '07345678901',
    company: 'Global Marketing Co',
    address: '789 Queen Street, Birmingham',
  },
  {
    name: 'Emma Davis',
    email: 'emma.davis@example.com',
    phone: '07456789012',
    company: 'Innovation Hub',
    address: '321 Park Lane, Leeds',
  },
  {
    name: 'James Wilson',
    email: 'james.wilson@example.com',
    phone: '07567890123',
    company: 'Future Systems',
    address: '654 High Street, Liverpool',
  },
  {
    name: 'Lisa Anderson',
    email: 'lisa.anderson@example.com',
    phone: '07678901234',
    company: 'Digital Ventures',
    address: '987 Market Square, Bristol',
  },
  {
    name: 'David Thompson',
    email: 'david.thompson@example.com',
    phone: '07789012345',
    company: 'Smart Solutions',
    address: '147 Church Lane, Newcastle',
  },
  {
    name: 'Rachel Green',
    email: 'rachel.green@example.com',
    phone: '07890123456',
    company: 'Modern Enterprises',
    address: '258 Victoria Road, Sheffield',
  },
  {
    name: 'Chris Taylor',
    email: 'chris.taylor@example.com',
    phone: '07901234567',
    company: 'Progressive Tech',
    address: '369 Station Road, Nottingham',
  },
  {
    name: 'Amy Roberts',
    email: 'amy.roberts@example.com',
    phone: '07012345678',
    company: 'Excellence Group',
    address: '741 Commercial Street, Cardiff',
  },
  {
    name: 'Thomas Mitchell',
    email: 'thomas.mitchell@example.com',
    phone: '07113456789',
    company: 'Blue Ocean Consulting',
    address: '852 Princess Street, Edinburgh',
  },
  {
    name: 'Sophie Clarke',
    email: 'sophie.clarke@example.com',
    phone: '07224567890',
    company: 'Quantum Analytics',
    address: '174 Castle Street, Glasgow',
  },
  {
    name: 'Robert Turner',
    email: 'robert.turner@example.com',
    phone: '07335678901',
    company: 'Prime Logistics',
    address: '963 Royal Mile, Edinburgh',
  },
  {
    name: 'Jessica Parker',
    email: 'jessica.parker@example.com',
    phone: '07446789012',
    company: 'Stellar Communications',
    address: '485 George Square, Glasgow',
  },
  {
    name: 'Daniel Harris',
    email: 'daniel.harris@example.com',
    phone: '07557890123',
    company: 'Alpha Dynamics',
    address: '697 Union Street, Aberdeen',
  },
  {
    name: 'Hannah White',
    email: 'hannah.white@example.com',
    phone: '07668901234',
    company: 'Vivid Design Studio',
    address: '318 Broad Street, Oxford',
  },
  {
    name: 'Matthew Lewis',
    email: 'matthew.lewis@example.com',
    phone: '07779012345',
    company: 'Matrix Technologies',
    address: '529 Mill Road, Cambridge',
  },
  {
    name: 'Olivia Young',
    email: 'olivia.young@example.com',
    phone: '07880123456',
    company: 'Emerald Solutions',
    address: '741 North Street, Brighton',
  },
  {
    name: 'Benjamin King',
    email: 'benjamin.king@example.com',
    phone: '07991234567',
    company: 'Phoenix Enterprises',
    address: '862 South Road, Portsmouth',
  },
  {
    name: 'Grace Scott',
    email: 'grace.scott@example.com',
    phone: '07102345678',
    company: 'Horizon Media',
    address: '193 East Street, Southampton',
  },
  {
    name: 'Alexander Wright',
    email: 'alexander.wright@example.com',
    phone: '07213456789',
    company: 'Velocity Ventures',
    address: '574 West End, Leicester',
  },
  {
    name: 'Charlotte Adams',
    email: 'charlotte.adams@example.com',
    phone: '07324567890',
    company: 'Aurora Creative',
    address: '685 Central Avenue, Coventry',
  },
  {
    name: 'William Baker',
    email: 'william.baker@example.com',
    phone: '07435678901',
    company: 'Summit Strategies',
    address: '796 Park Road, Derby',
  },
  {
    name: 'Isabella Hall',
    email: 'isabella.hall@example.com',
    phone: '07546789012',
    company: 'Crystal Clear Consulting',
    address: '207 Garden Street, Stoke-on-Trent',
  },
  {
    name: 'Henry Allen',
    email: 'henry.allen@example.com',
    phone: '07657890123',
    company: 'Infinite Innovations',
    address: '418 Church Street, Preston',
  },
  {
    name: 'Amelia Collins',
    email: 'amelia.collins@example.com',
    phone: '07768901234',
    company: 'Bright Future Holdings',
    address: '529 Victoria Street, Blackpool',
  },
  {
    name: 'Jack Murphy',
    email: 'jack.murphy@example.com',
    phone: '07879012345',
    company: 'Dynamic Systems',
    address: '640 Market Street, Bolton',
  },
  {
    name: 'Mia Cooper',
    email: 'mia.cooper@example.com',
    phone: '07980123456',
    company: 'Nexus Networks',
    address: '751 High Road, Oldham',
  },
  {
    name: 'George Reed',
    email: 'george.reed@example.com',
    phone: '07091234567',
    company: 'Pinnacle Properties',
    address: '862 Main Street, Rochdale',
  },
  {
    name: 'Ella Ward',
    email: 'ella.ward@example.com',
    phone: '07192345678',
    company: 'Radiant Resources',
    address: '973 Station Road, Stockport',
  },
]
