export const products = [
  {
    id: 'P001',
    name: 'Wireless Headphones',
    price: 129.99,
    stock: 45,
    category: 'Electronics',
    supplier: 'AudioTech',
    reorderPoint: 15,
    lastRestocked: '2024-01-15',
  },
  {
    id: 'P002',
    name: 'Smart Watch',
    price: 199.99,
    stock: 32,
    category: 'Electronics',
    supplier: 'TechGear',
    reorderPoint: 10,
    lastRestocked: '2024-01-10',
  },
  {
    id: 'P003',
    name: 'Running Shoes',
    price: 89.99,
    stock: 78,
    category: 'Sports',
    supplier: 'SportsFit',
    reorderPoint: 20,
    lastRestocked: '2024-01-20',
  },
  {
    id: 'P004',
    name: 'Water Bottle',
    price: 24.99,
    stock: 120,
    category: 'Sports',
    supplier: 'EcoWare',
    reorderPoint: 30,
    lastRestocked: '2024-01-05',
  },
  {
    id: 'P005',
    name: 'Laptop Bag',
    price: 59.99,
    stock: 25,
    category: 'Accessories',
    supplier: 'BagMasters',
    reorderPoint: 12,
    lastRestocked: '2024-01-18',
  },
]
